### ISSUE TITLE
[1.18.2 Forge Bug]: Fails to launch: noClassDefFound

### ISSUE THREAD

**Issue by The-Professor123** [DragonSurvivalTeam/DragonSurvival#229] opened 2022-11-04 01:09 UTC
### ■ Your Discord ID

AbsoluteMax123#0978

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.18.2-1.4.31.jar

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configurations and check the Wiki before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

![image](https://user-images.githubusercontent.com/92767299/199863193-a7e423ed-de84-4970-b193-480117abef46.png)

### ■ To Reproduce

launch the game with the following mods: (sorry for mess was pasted from HTML)
[Upgraded Netherite : Items (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-items)
[Upgraded Netherite : Ultimerite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-ultimerite)
[Paintings with Dragons (by BlackAuresArt)](https://www.curseforge.com/minecraft/mc-mods/paintings-with-dragons)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Dragon Survival [Forge] (by BlackAuresArt)](https://www.curseforge.com/minecraft/mc-mods/dragons-survival)
[Upgraded Core (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-core)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Upgraded Netherite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite) 

### ■ Expected behavior

Launching without issue.

### ■ Crash Report

[crash-2022-11-03_18.00.45-fml.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/9934109/crash-2022-11-03_18.00.45-fml.txt)

**Comment by Horeak** [comment] 2022-11-04 01:39
Update to a forge version that is at least number 40.1.67 or newer.

Duplicate of #227

**Closed by Horeak** 2022-11-04 01:39 UTC
Labels: bug
