### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ginjuri** [DragonSurvivalTeam/DragonSurvival#136] opened 2022-03-31 16:44 UTC
### ■ Your Discord ID

David Dent#7178

### ■ Dragon Survival version

Not sure what to put here I guess I'll just add the version from Curse Forge as written data?

Dragon Survival
by BlackAuresArt

RDragonSurvival_DragonEditor-1.16.5-0.10.1.jar
173.6K
2 days ago
6.14 MB
1.16.5
Forge

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

I'm quite happy this new feature "Dragon Editor" except if I try to use it in survival through curse forge it crashes the game giving me this error:

The game crashed whilst ticking player
Error: java.lang.ArrayIndexOutOfBoundsException: 2
Exit Code: -1

I have tried loading survival worlds and eliminating mods to see if it was a conflict but so far it's only when I have it set to survival and try to use the Dragon Altar to Save the skin. I can possibly make a video on it if you need to see what happened.

### ■ To Reproduce

The game crashed whilst ticking player
Error: java.lang.ArrayIndexOutOfBoundsException: 2
Exit Code: -1

### ■ Expected behavior

The editor to save the skin and let me continue on my way in survival I suppose.

### ■ Crash Report

The game crashed whilst ticking player
Error: java.lang.ArrayIndexOutOfBoundsException: 2
Exit Code: -1

**Comment by BlackAures1** [comment] 2022-03-31 16:59
delete all the configs according to the instructions and make sure you have installed geckolib https://dragons-survival.fandom.com/wiki/Start_and_Setting

**Comment by Horeak** [comment] 2022-04-01 10:05
Duplicate of #131 which has been resolved and will be made available soon

**Closed by Horeak** 2022-04-01 10:05 UTC
Labels: bug
