### ISSUE TITLE
[1.19.2 Forge Bug]: Server config corrected unnecessarily, sometimes causes crash

### ISSUE THREAD

**Issue by MozarteanChaos** [DragonSurvivalTeam/DragonSurvival#354] opened 2023-08-10 22:15 UTC
### ■ Your Discord ID or other contacts

MozarteanChaos (discord username)

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.57

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

Description: Every time a world is opened, the mod corrects that world's server config, even if nothing in that config has been changed. This sometimes causes the game to crash, although it's pretty inconsistent.
The game also fails to close when crashing this way, requiring the user to close it manually.
This first happened in my larger modpack, but the files attached are from when I tested it with only Dragon Survival and GeckoLib.
I think this may be related to the problems I keep having with changing what each type of dragon can eat, since that's controlled by the server config, but I don't have enough technical knowledge to test that...

Steps to reproduce: Create a new world, or open one you've already made.
Possibly observe Minecraft crashing while trying to open the world.
Check the latest log file for the mod correcting the server config.

### ■ Expected behavior

I expect the mod to leave its server config files alone if there's nothing wrong with them, and to not crash the game when it tries to correct problems with them.

### ■ Crash Report File and Logs

[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12317493/latest.log)
[crash-2023-08-10_23.08.55-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12317495/crash-2023-08-10_23.08.55-server.txt)

**Comment by MozarteanChaos** [comment] 2023-08-22 02:36
Update:
https://github.com/DragonSurvivalTeam/DragonSurvival/commit/ed28158274f1ae7000ee6c54c88b0423115b951b seems to have stopped this from happening when loading a world that already exists, but not when making a new one. I think this implies some kind of issue with the process of automatically editing the config, but I don't know enough about how that works to provide any useful information, aside from some more logs.

I'm glad to see the issue's closer to being fixed, though! The update also fixed the problems I kept having with my edits to the server config file not being applied properly, so that's a nice bonus.

Here are the new logs:
[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12404059/latest.log)
[crash-2023-08-22_03.25.05-server.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12404076/crash-2023-08-22_03.25.05-server.txt)
The full log's a bit longer than last time, but that's just because it took a couple of attempts to reproduce the issue.

**Comment by SiverDX** [comment] 2023-08-22 05:48
The general correcting is something that comes from forge itself since the config file gets created when you create a new world
(unless you placed the server config in the `defaultconfig` directory)

the problem is a second correcting from a different thread due to an incorrect config value, see https://github.com/DragonSurvivalTeam/DragonSurvival/pull/359/commits/ca17cc98dc527c2bc0ddc7d9c0312a15f26017eb

`undergarden:ditchbulb:5,6` -> `undergarden:ditchbulb:5:6`

**Comment by MozarteanChaos** [comment] 2023-08-22 06:54
> The general correcting is something that comes from forge itself since the config file gets created when you create a new world (unless you placed the server config in the `defaultconfig` directory)
> 
> the problem is a second correcting from a different thread due to an incorrect config value, see [ca17cc9](https://github.com/DragonSurvivalTeam/DragonSurvival/commit/ca17cc98dc527c2bc0ddc7d9c0312a15f26017eb)
> 
> `undergarden:ditchbulb:5,6` -> `undergarden:ditchbulb:5:6`

Huh, good to know.
I do wonder why it so inconsistently caused a crash, but I guess some things just work strangely. Computers are weird, I dunno.

Anyway, if that ends up fixing the issue (as far as you can tell, at least; with how inconsistent the crash is, I can't really expect anyone to sit there testing for hours just in case) then I'm cool with this issue being closed 👍

**Comment by BlackAures1** [comment] 2023-08-22 07:31
I take it it was the forge itself that broke something? Because this config with this erroneous value has existed since February of this year. https://github.com/DragonSurvivalTeam/DragonSurvival/commit/f8db348ee452621f6e6329148089bead2bd2d2e2
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/43911230/1061d76b-a2c8-4ddd-a726-d894bfed7dfd)

**Comment by BlackAures1** [comment] 2023-08-22 10:20
Is this line necessary? The unnecessary crashes on something that works is not something that I and other users would be happy to see

**Comment by SiverDX** [comment] 2023-08-22 11:10
yes

you dont want random gibberish in a config (this could lead to other issues) and if they edit it through any ingame config editor they will not be able to input wrong values anyway (only if they edit the file directly)

this is a problem of broken configs (and the default shipped configs will be fixed with https://github.com/DragonSurvivalTeam/DragonSurvival/commit/ca17cc98dc527c2bc0ddc7d9c0312a15f26017eb)

**Comment by BlackAures1** [comment] 2023-11-13 04:00
If I remember correctly, this problem has been resolved. Will reopen if not fixed

**Closed by BlackAures1** 2023-11-13 04:00 UTC
Labels: bug
