### ISSUE TITLE
[1.19.2 Bug]: Incompatibility - Enlightened End breaks Lava Vision

### ISSUE THREAD

**Issue by DragonGirl42** [DragonSurvivalTeam/DragonSurvival#475] opened 2024-05-13 15:55 UTC
### ■ Your Discord ID or other contacts

peridotyoshi

### ■ Dragon Survival version

DragonSurvival-1.19.2-02.03.2024_stable.jar

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

I've been working on a modpack for myself and my friends, and I was testing as a Cave Dragon when I noticed my Lava Vision wasn't allowing me to see under the lava. Activating it while above the lava allows me to see thought it, but as soon as I submerse my camera, it's as foggy as always, as though I don't have the Lava Vision effect at all!

I tested every mod I'd bundled together with Dragon Survival, and found the problem to be the presence of the Enlightened End mod. Without this mod, the rest of the modpack plays just fine with Lava Vision.

Reproduction Steps:
1. Install Dragon Survival, Geckolib, and Enlightened End
2. Open the game, create new world or use existing world
3. Become a Cave Dragon, and find or place some lava
4. Activate Lava Vision and submerse in the lava

Expected Behavior:
Vision is clearer under the lava

Actual Behavior:
Vision is foggy and limited under the lava, as it would be without the Lava Vision effect

**Comment by BlackAures1** [comment] 2024-05-25 19:55
It's unlikely that this bug needs to be written to us. Possible solutions would just break our skill or cease to be compatible with shaders.

**Comment by seelderr** [comment] 2024-05-26 19:08
It is possible this will be fixed with a rework to how Lava Vision works in 1.20.1. Will retest this when I have time.

**Comment by DragonGirl42** [comment] 2024-06-18 18:31
Since Lava Vision was just reworked for the latest version of Dragon Survival (1.19.2-16.06.2024), I gave it a quick look with the EnlightEnd mod. Even though lava looks more transparent from above the surface, it's unfortunately still completely foggy beneath the surface.

**Comment by SiverDX** [comment] 2024-11-16 02:24
This is caused by `Enlightend` setting the `ViewportEvent.RenderFog` as cancelled even though they only do modifications when in the end dimension

(Setting an event to cancelled prevents other mods from receiving it unless the specifically request for it and for this event in particular it means that you did some modifications, which in this case is not true - so a bug on their end)

See `EndRenderingProcedure` and `RenderSkyboxProcedure`
(This seems how MCreator handles that event so this incompatibility could be present with other mods from there)

**Comment by SiverDX** [comment] 2024-11-17 03:00
Fixed in `1.19.2-16.11.2024`

**Closed by SiverDX** 2024-11-17 03:00 UTC
Labels: bug, compatibility, 1.19.2
