### ISSUE TITLE
[1.19.2 Forge Bug]: incorrect duration

### ISSUE THREAD

**Issue by Smugi99** [DragonSurvivalTeam/DragonSurvival#308] opened 2023-05-25 14:20 UTC
### ■ Your Discord ID or other contacts

Smugi#7860

### ■ Dragon Survival version and Modpack version (if have)

DragonSurvival-1.19.2-1.5.42

### ■ Single game or server?

Dedicated Server or Host Sites

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Bug Description and Reproduce

Level 3 Sturdy Skin only giving 180secs duration

### ■ Expected behavior

Skill info says 3600seconds of duration at level 3

**Comment by FirDragon** [comment] 2023-05-29 01:24
Thanks for submitting, this issue is a duplicate of #261.

**Closed** 2023-11-13 04:05 UTC
Labels: bug, duplicate
