### ISSUE TITLE
[Compatibility]: Arclight crash with DS on Magma Core (not Forge)

### ISSUE THREAD

**Issue by RDS616616** [DragonSurvivalTeam/DragonSurvival#362] opened 2023-08-26 04:25 UTC
### ■ Your Discord ID

_gashadokuro_

### ■ Dragon Survival version

DragonSurvival-1.19.2-1.5.56

### ■ Minecraft version

1.18

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

Nope (Default)

### ■ Description of incompatibility

I have had a constant error on my dedicated server, when I am a dragon in survival mode I cannot open the inventory, it takes me directly from the server giving the Internal Exception error: java.lang.IllegalStateException: InventoryOpenEvent cannot be triggered asynchronously from another thread.
And in creative mode it lets me access the vanilla inventory but when I open the dragon inventory it gives me the same error, only on the single player server everything works fine

### ■ To Reproduce

can not be replicated, it only happens on my server

**Comment by SiverDX** [comment] 2023-08-26 09:41
Need logs (latest.log) and list of mods you use
Also I don't know any `InventoryOpenEvent` - are you using plugins (e.g. Bukkit)?

Can't reproduce the issue with just Dragon Survival - opening / closing inventory etc. works fine in single- and multiplayer

**Comment by RDS616616** [comment] 2023-08-26 12:33
https://mega.nz/file/ynhU3LwS#T9BfrJrqGPm7ab8Zz6Vd0PZER2qIoBrbNShb_QQfzFE These are the mods I'm currently using on my server And these are the plugins
AdminUsefulCommands - AUC- 1.5
EconomyShopGUI-5.6.5
EssentialsX-2.19.7
Konquest- 0.12.0
LoginSecurity-3.2.0-Bukkit
PicoJobs-1.0-beta-7a
Shopkeepers-2.17.1
WorldEdit-bukkit-7-2-12
WorldGuard-bukkit-7.0.8-dist
And this is te last.log

[2023-08-25-1.log.gz](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12445338/2023-08-25-1.log.gz)

**Comment by SiverDX** [comment] 2023-08-26 13:08
And the client log?

Though this might be more of a bukkit / forge compatibility thing

**Comment by RDS616616** [comment] 2023-08-26 13:10
[2023-08-26-3.log.gz](https://github.com/DragonSurvivalTeam/DragonSurvival/files/12445411/2023-08-26-3.log.gz)

**Comment by BlackAures1** [comment] 2023-08-26 13:16
Magma  core?

**Comment by SiverDX** [comment] 2023-08-26 13:20
they're using https://github.com/IzzelAliz/Arclight

though I can't find anything about that error in either of those logs

**Comment by RDS616616** [comment] 2023-08-26 13:22
So what do you recommend me to do?

**Comment by BlackAures1** [comment] 2023-08-26 13:39
Sorry, but we only support Forge. All server cores that detail crutches to connect mods and plugins usually work horribly

**Comment by RDS616616** [comment] 2023-08-26 13:49
I already solved it, change arclight for mohist and it works perfectly

**Comment by BlackAures1** [comment] 2023-08-26 14:12
There are a lot of problems with mohist as well. You should look for analog mods for the plugins you are using.  There are quite a lot of options.

**Comment by seelderr** [comment] 2024-05-26 19:40
WNF for now as per above

**Closed by seelderr** 2024-05-26 19:40 UTC
Labels: bug, crash
