### ISSUE TITLE
[1.20.1 Bug]: 

### ISSUE THREAD

**Issue by HakeT2Lab** [DragonSurvivalTeam/DragonSurvival#442] opened 2024-03-08 22:57 UTC
### ■ Your Discord ID or other contacts

ItzalGaming#4212

### ■ Dragon Survival version

DragonSurvival-1.20.1-09.01.2024

### ■ Forge/Neoforge version

Forge-47.2.0

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

On an existing world where player was already a dragon, running the kill command would sometimes result in player pov being reset to vanilla pov's height. Simply crouching would fix it(note: some mods seem to prevent this as I've found when using dragon survival in other modpacks.). However upon using the alter to turn into a human and back to a dragon resulted in the same bug referred to in #435 with the player not being able to respawn.

I am unsure if the mod was updated after the world was created.

### ■ Crash Report File and Logs

[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/14543869/latest.log)

**Comment by seelderr** [comment] 2024-05-26 19:24
Won't be fixing issues with the respawn screen for now, WNF.

**Comment by seelderr** [comment] 2024-05-26 19:30
This is a dupe of #435 and has been fixed

**Closed by seelderr** 2024-05-26 19:30 UTC
Labels: bug, 1.20.1
