### ISSUE TITLE
[Compatibility]: 

### ISSUE THREAD

**Issue by Starry-Sunrise** [DragonSurvivalTeam/DragonSurvival#187] opened 2022-08-02 15:23 UTC
### ■ Your Discord ID

-StarrySunrise-#1059

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.6.jar.jar

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

If I have both _Dragon Survival_ and _Forbidden and Arcanus_ installed at the same time, I cannot respawn under any circumstances.
Clicking the respawn button does not do anything, and returning to worlds where you died takes you back to that screen.

### ■ To Reproduce

1. Install _Dragon Survival_
2. Install _Forbidden and Arcanus_
3. Run the game
4. Die in game

**Comment by Horeak** [comment] 2022-08-02 16:32
Duplicate of #185

**Closed by Horeak** 2022-08-02 16:32 UTC
