### ISSUE TITLE
Crash when spreading Wings to fly

### ISSUE THREAD

**Issue by Jorgee9001** [DragonSurvivalTeam/DragonSurvival#14] opened 2021-05-09 19:01 UTC
1.16.5; My friend and I were playing as a sea dragon and cave dragon respectively. When we got our wings and activated them to fly, we both crashed within a few moments of taking off. Flight in Creative mode didn't cause any crashes.

[crash-2021-05-09_14.59.06-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/6448213/crash-2021-05-09_14.59.06-client.txt)

**Comment by Arcaryx** [comment] 2021-05-09 19:32
From what I can tell, this crash is somehow related to the fins and tails mod. In their playerTick method they handle some sort of custom flying packet (which is null). I don't know the reason for this but from what I can tell it is the cause of the crash.

**Comment by AlexiyOrlov** [comment] 2021-05-17 11:15
@Jorgee9001 confirm whether that it was caused by Fins and Tails mod, otherwise I will close this issue in 3 days.

**Comment by Jorgee9001** [comment] 2021-05-17 21:32
Just double checked. Seems to work fine when Fins and Tails is removed.

**Closed** 2021-10-02 19:06 UTC
