### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gamebusterzyde** [DragonSurvivalTeam/DragonSurvival#139] opened 2022-04-01 07:56 UTC
### ■ Your Discord ID

gamebusterzyde#4200

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.1.jar

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Do you play pure MC + DS and Geckolib or do you have some kind of modpack?

I have other mods

### ■ Describe the bug

crash out of game session. only crashes the player not the server

### ■ To Reproduce

add modded items to to hot bar. not all mod but mods found to crash are create, and refined storage. also had the crash happen when i tried to move elder dragon heart from inventory to the hot bar 

### ■ Expected behavior

game not crash when playing as a dragon

### ■ Crash Report

[latest.log](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8395713/latest.log)
[2022-03-31-5.log.gz](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8395719/2022-03-31-5.log.gz)
[2022-04-01-1.log.gz](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8395720/2022-04-01-1.log.gz)
[2022-03-31-4.log.gz](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8395721/2022-03-31-4.log.gz)

**Comment by Horeak** [comment] 2022-04-01 10:08
Possible duplicate of #131 but it would be helpful if you could post the crash report rather then the log. (Found under the "crash-reports" folder instead of "logs")

**Comment by gamebusterzyde** [comment] 2022-04-01 21:00
[crash-2022-04-01_02.06.49-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8400879/crash-2022-04-01_02.06.49-client.txt)
[crash-2022-04-01_01.50.49-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8400880/crash-2022-04-01_01.50.49-client.txt)
[crash-2022-04-01_01.45.52-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8400881/crash-2022-04-01_01.45.52-client.txt)
[crash-2022-04-01_01.37.55-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8400882/crash-2022-04-01_01.37.55-client.txt)
[crash-2022-04-01_01.21.28-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8400883/crash-2022-04-01_01.21.28-client.txt)
[crash-2022-04-01_02.33.24-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8400884/crash-2022-04-01_02.33.24-client.txt)
[crash-2022-04-01_02.12.47-client.txt](https://github.com/DragonSurvivalTeam/DragonSurvival/files/8400885/crash-2022-04-01_02.12.47-client.txt)

**Comment by Horeak** [comment] 2022-04-01 21:02
Yeah that is a duplicate of #131 so a fix should be released soon but the exact time will be up to @BlackAures1

**Closed by Horeak** 2022-04-01 21:02 UTC
Labels: bug, duplicate

**Comment by gamebusterzyde** [comment] 2022-04-01 21:06
thanks for the info, will pass that on to my server.
