### ISSUE TITLE
[1.19.2 Forge Bug]: Dragon Editor causes Memory Leaks

### ISSUE THREAD

**Issue by Gronglegrowth** [DragonSurvivalTeam/DragonSurvival#382] opened 2023-11-16 21:21 UTC
### ■ Your Discord ID or other contacts

Discord: esetkalenko

### ■ Dragon Survival version and Modpack version (if have)

Dragon Survival 1.19.2.10.11.2023

### ■ Single game or server?

Single (Default)

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Bug Description and Reproduce

When using the Dragon Editor and selecting parts, the ram usage of the java process will keep going up past normal levels, thus a memory leak.

To reproduce this:
1. Create a new world
2. Select any dragon type
3. Play around in the Editor, select parts, recolor them, etc
4. Observe the ram usage increase during

### ■ Expected behavior

When using the Dragon Editor, no memory leaks should occur.

**Comment by SiverDX** [comment] 2023-11-16 21:53
can't reproduce

memory is stable on new instance and when i changed a lot in the editor, incl. opening, closing and saving multiple times

![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/22003703/0c92896c-1aff-42ec-8159-0f4f78762bfd)

**Comment by Gronglegrowth** [comment] 2023-11-16 22:40
It does definitely happen to me, in an instance with only this mod and its dependency Geckolib; 4gb of ram allocated to the game, and it is consuming vastly more than this as this screenshot shows:
![Screenshot_20231116_173945](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/32804557/60cd2e94-eae1-4a27-9019-70920472d81e)

**Comment by BlackAures1** [comment] 2023-11-16 22:53
The only lag that happens in the Dragon Editor is the lag at the moment of color/saturation change.

**Comment by druidicmage** [comment] 2023-11-16 23:29
This just happened to me too. Getting too into customization crashed my Discord, then my Minecraft, and then broke my discord. To be clear, I have a good computer and allocated ~13GB for this. Lag in the editor is very noticeable when moving the sliders and changing the customization options.

**Comment by LeoBeliik** [comment] 2023-11-16 23:30
I can easily reproduce this, every time I press a button in the dragon editor the memory heap increases, this even happens pressing the reset to default button multiple times in a row
![image](https://github.com/DragonSurvivalTeam/DragonSurvival/assets/11804768/1c667933-431e-496b-8dd1-f8ed44e6d021)

geckolib-forge-1.19-3.1.40
DragonSurvival-1.19.2-10.11.2023_GLOBAL_UPDATE_READ_PATCH_NOTE
forge 43.3.5
tested it with java 17 & 18

**Comment by Notmyname600** [comment] 2023-11-16 23:45
Dragonsurvival1.19.2-10.11.2023_GLOBAL.jar
Geckolib-forge-1.19-3.1.40.jar
Forge 1.19.2 43.3.5
Go f5 around a dragon player to reproduce a crash that kills your graphics card and any apps you were in that aren't involved with MC

**Closed** 2023-11-17 09:19 UTC
Labels: bug
