### ISSUE TITLE
[1.20.1 Bug]: 

### ISSUE THREAD

**Issue by StrunVul** [DragonSurvivalTeam/DragonSurvival#622] opened 2024-08-01 11:49 UTC
### ■ Your Discord ID or other contacts

strunvul#9675

### ■ Dragon Survival version

v1.5.57

### ■ Forge/Neoforge version

v47.3.5

### ■ Single game or server?

Single-player (Default)

### ■ Describe the bug

Addons for Create or mods Alex Caves-Mobs Breaks head hitbox. Sometimes breaks with others mods which use geckolib. Removing all configs not help. Also new version of Jei not working well with dragon inventory. (EDIT: Found the same problem here, and 
![image](https://github.com/user-attachments/assets/ca46d93e-daf6-4049-b0d9-668085642f28)
 Alex Mobs not breaking hitbox, Alex Caves do. So better not play with Alex Cave. Screenshot after deleting mod Alex Caves.)

### ■ Crash Report File and Logs

![image](https://github.com/user-attachments/assets/70307bef-ed73-4959-8c6f-4e9014b2faa7)
![image](https://github.com/user-attachments/assets/47fc7018-4127-410d-83b2-00da568f83c2)

**Comment by KJEntytek303** [comment] 2024-08-01 16:29
but there is no dragon survival version v1.5.57

**Comment by seelderr** [comment] 2024-09-01 21:30
Dupe of #444

**Closed by seelderr** 2024-09-01 21:30 UTC
Labels: bug
