### ISSUE TITLE
[Compatibility]: Crash when switching from Creative Mode to Survival Mode.

### ISSUE THREAD

**Issue by AStrangeMouse** [DragonSurvivalTeam/DragonSurvival#138] opened 2022-04-01 01:30 UTC
### ■ Your Discord ID

Mousy#2784

### ■ Dragon Survival version

DragonSurvival_DragonEditor-1.16.5-0.10.1

### ■ Minecraft version

1.16.5 (Default)

### ■ Single game or server?

Forge Server or host

### ■ Do you delete old configs before writing a bug report?

I always delete configs

### ■ Description of incompatibility

When playing as a dragon, switching from Creative Mode to Survival Mode causes the client to immediately crash. Attempting to reconnect to the server from then on throws an error and disconnects the player, disallowing them to rejoin until their player data has been deleted.

### ■ To Reproduce

Become a dragon, enter Creative Mode, and then exit into Survival Mode. Attempt to reconnect to the server.

### ■ Crash Report

https://pastebin.com/CiUMg7fR

**Comment by AStrangeMouse** [comment] 2022-04-01 02:44
Deleting the **saved_customizations.json** file has eliminated the crash. (The current changelog for this version states to keep this file if you wish to keep your dragon customization.)

**Comment by Horeak** [comment] 2022-04-01 10:02
Duplicate of #131 which has been resolved and will be made available soon

**Closed by Horeak** 2022-04-01 10:02 UTC
